// Generated by IB v0.4.3 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface HelloViewController: UIViewController

@property IBOutlet UIButton * button1;
@property IBOutlet UITextField * field1;

-(IBAction) doAction:(id) sender;

@end

